# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f72cc2837b7c6bbb191bf3358ff81e03e8fcafd7bbf00587f8dc974586aa416db412502cc90638e2486c2deac58c4532d4f058827533303b8a484ff87edb2c

test:
  secret_key_base: a8d64e8ab2742b37cfeba751057f9c445993ff72088a031b2ad722f541187658ac57ff2947d80de9a6acfd4f3b581940270cac52844cc91c93d82ae8878100a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
